Update 50-klipper

diff --git a/modules/generic/50-klipper b/modules/generic/50-klipper
--- a/modules/generic/50-klipper
+++ b/modules/generic/50-klipper
@@ -6,26 +6,36 @@ export LC_ALL=C
 # Functions and Basic Configuration    #
 ########################################
 
+# Load common functions and set up cleanup trap
 source /common.sh
 install_cleanup_trap
 
+# Load additional configuration (e.g., BASE_USER)
 source /files/00-config
 
 ########################################
 # Configuration                        #
 ########################################
 
-SRC_DIR="/home/${BASE_USER}/KlipperScreen"
+SRC_DIR="/home/${BASE_USER}/klipper"
+ENV_DIR="/home/${BASE_USER}/klippy-env"
+
 REPO="https://github.com/my-dudhwala/my-klipper"
 
 DEPS=(git \
-      python3 python3-pip python3-dev \
-      libffi-dev libssl-dev \
-      libjpeg-dev zlib1g-dev \
-      libgl1-mesa-dev libglvnd-dev \
-      libmtdev-dev \
-      xinput x11-xserver-utils \
-      libatlas-base-dev libopenblas-dev \
+      # Packages for python cffi
+      virtualenv python3-dev libffi-dev build-essential \
+      # kconfig requirements
+      libncurses-dev pkg-config \
+      # hub-ctrl
+      libusb-dev libusb-1.0-0-dev \
+      # AVR chip installation and building
+      avrdude gcc-avr binutils-avr avr-libc \
+      # ARM chip installation and building
+      stm32flash dfu-util libnewlib-arm-none-eabi \
+      gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0-0 \
+      # Input shaper dependencies
+      python3-numpy python3-matplotlib libatlas-base-dev libopenblas-dev \
       )
 
 ########################################
@@ -36,24 +46,46 @@ echo "Installing Dependencies"
 apt-get install --yes "${DEPS[@]}"
 
 ########################################
-# Clone Repository                     #
+# Add user to groups                   #
+########################################
+
+## Make sure user pi has access to serial ports
+usermod -a -G "tty,dialout" "${BASE_USER}"
+
+########################################
+# Switch into home dir                 #
 ########################################
 
 pushd "/home/${BASE_USER}" &> /dev/null || exit 1
 
-if [ ! -d "${SRC_DIR}" ]; then
-  echo "Cloning KlipperScreen repo..."
-  sudo -u "${BASE_USER}" git clone "${REPO}" KlipperScreen
-else
-  echo "KlipperScreen already exists, skipping clone."
-fi
-
 ########################################
-# Install Python Requirements          #
+# Clone repository                     #
 ########################################
 
-echo "Installing Python Requirements..."
-sudo -u "${BASE_USER}" pip3 install -r "${SRC_DIR}/requirements.txt"
+echo "Cloning repo ..."
+sudo -u "${BASE_USER}" git clone ${REPO} klipper
+
+########################################
+# Create printer_data directories      #
+########################################
+
+create_user_directories
+
+########################################
+# Create Virtualenv and install        #
+# dependencies                         #
+########################################
+
+echo "Creating Virtualenv (klippy-env) ..."
+sudo -u "${BASE_USER}" virtualenv -p python3 "${ENV_DIR}"
+echo "Installing Python Dependencies ..."
+sudo -u "${BASE_USER}" "${ENV_DIR}"/bin/pip install -r "${SRC_DIR}"/scripts/klippy-requirements.txt
+echo "Installing NumPy in Virtualenv"
+sudo -u "${BASE_USER}" "${ENV_DIR}"/bin/pip install "numpy<1.26"
+
+########################################
+# Return to saved directory            #
+########################################
 
 popd &> /dev/null || exit 1
 
@@ -62,5 +94,7 @@ popd &> /dev/null || exit 1
 ########################################
 
 echo "Copy Service and enable it"
-cp /files/klipperscreen.service /etc/systemd/system/klipperscreen@.service
-systemctl_if_exists enable klipperscreen@${BASE_USER}.service
+cp /files/klipper.service /etc/systemd/system/klipper.service
+cp /files/klipper.env /home/"${BASE_USER}"/printer_data/systemd/klipper.env
+chown -R "${BASE_USER}":"${BASE_USER}" /home/"${BASE_USER}"/printer_data/systemd/klipper.env
+systemctl_if_exists enable klipper.service
